data:
  data_dir: "/shared/cooney_lab/Shared/data/hyperspectral/lepidoptera" # "/fastdata/bi1ei/Multispec_test_images"Multispec_test_images_5000
  # data_dir: "/mnt/xdrive/cooney_lab/Shared/RSE/Image_sets/Passerines-Segmented-Back-RGB-PNG"

output:
  out_dir: "/shared/cooney_lab/Shared/Eleftherios-Ioannou/SimCLR/hyperspectral/"
  # out_dir: "/mnt/xdrive/cooney_lab/Shared/RSE/01_embeddings"

model:
  name: 'simclr'  # not yet configurable
  backbone: 'vit_l_16'
  weights: 'ViT_L_16_Weights' # https://pytorch.org/vision/stable/models.html

  optimizer:
    lr: 0.001

  scheduler:
    name: 'CosineAnnealingLR'  # not yet configurable
    params:
      T_max: 200
      eta_min: 0.001

  criterion:
    type: 'global'
    global_weight: 1.0
    local_weight: 1.0
    name: 'NTXentLoss'  # not yet configurable
    use_local_loss: false
    params:
      temperature: 0.1
      

seed: 1

dataloader:
  num_workers: 16
  batch_size: 8

train:
  deterministic: true  # for reproducible runs
  accelerator: 'auto'
  devices: 'auto' # or 1 or 2
  max_epochs: 100
  log_every_n_steps: 25 # ideally one log for each epoch (= number of steps per epoch)


augmentations:
  input_size: 224

  transforms:

    random_resize_crop:
      enabled: true
      size: [224, 224]
      scale: [0.05, 1.0]  
      p: 1.0
    
    color_jitter:
      enabled: false
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
      p: 0.8
    
    grayscale:
      enabled: false
      p: 0.1
    
    gaussian_blur:
      enabled: true
      sigma_limit: [0.1, 2.0]
      p: 0.25 
    
    vertical_flip:
      enabled: true
      p: 0.5

    horizontal_flip:
      enabled: false
      p: 0.5

    rotate:
      enabled: true
      limit: 45
      p: 0.5
    
    gaussian_noise:
      enabled: false
      mean_range: [0, 0]
      std_range: [0.05, 0.1]
      p: 0.2
    
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    
    thin_plate_spline:
      enabled: true
      scale: 0.5
      p: 0.5
    
    random_perspective:
      enabled: true
      distortion_scale: 0.5
      p: 0.5
    
    random_sharpness:
      enabled: false
      sharpness: 0.5
      p: 0.5
    
    random_posterize:
      enabled: false
      bits: 3
      p: 0.5 
    
    random_erasing:
      enabled: true 
      scale: [0.02, 0.33]
      p: 0.25
    