data:
  # Support for multiple datasets
  data_dirs:
    - "/fastdata/bi1ei/Passerines-Segmented-Back-RGB-PNG"  # Back view dataset
    - "/fastdata/bi1ei/Passerines-Segmented-Side-RGB-PNG"  # Side view dataset
  # For backward compatibility
  data_dir: "/fastdata/bi1ei/Passerines-Segmented-Back-RGB-PNG"

  # data_dir: "/mnt/xdrive/cooney_lab/Shared/RSE/Image_sets/Passerines-Segmented-Back-RGB-PNG"

output:
  out_dir: "embeddings/12_embeddings"
  # out_dir: "/mnt/xdrive/cooney_lab/Shared/RSE/01_embeddings"

model:
  name: 'simclr'  # not yet configurable
  backbone: 'resnet50'
  weights: 'IMAGENET1K_V2' # https://pytorch.org/vision/stable/models.html

  optimizer:
    lr: 0.001

  scheduler:
    name: 'CosineAnnealingLR'  # not yet configurable
    params:
      T_max: 200
      eta_min: 0.001

  criterion:
    name: 'NTXentLoss'  # not yet configurable
    params:
      temperature: 0.1

seed: 1

dataloader:
  num_workers: 16
  batch_size: 72

train:
  deterministic: true  # for reproducible runs
  accelerator: 'gpu'
  devices: 'auto' # or 1 or 2
  max_epochs: 200
  log_every_n_steps: 25 # ideally one log for each epoch (= number of steps per epoch)


augmentations:
  input_size: 224

  transforms:

    random_resize_crop:
      enabled: true
      size: [224, 224]
      scale: [0.5, 1.0]  
      p: 1.0
    
    color_jitter:
      enabled: false
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
      p: 0.8
    
    grayscale:
      enabled: true
      p: 0.1
    
    gaussian_blur:
      enabled: true
      sigma_limit: [0.1, 2.0]
      p: 0.5 
    
    vertical_flip:
      enabled: true
      p: 0.5

    horizontal_flip:
      enabled: false
      p: 0.5

    rotate:
      enabled: true
      limit: 45
      p: 0.5
    
    gaussian_noise:
      enabled: false
      mean_range: [0, 0]
      std_range: [0.05, 0.1]
      p: 0.2
    
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    
    thin_plate_spline:
      enabled: true
      scale: 0.5
      p: 0.25
    
    random_perspective:
      enabled: true
      distortion_scale: 0.5
      p: 0.25
    
    random_erasing:
      enabled: true 
      scale: [0.02, 0.33]
      p: 0.25
    
    random_sharpness:
      enabled: false 
      sharpness: 0.5
      p: 0.25
    
    random_posterize:
      enabled: false 
      bits: 3
      p: 0.5 